version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.22.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - backend_service

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "50051:50051"

  backend_service:
    build:
      context: ./backend_service
    ports:
      - "8012:8012"


