version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.27.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"

  auth_service:
    build: ./auth_service
    ports:
      - "50051:50051"
