services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: embeddings
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


  pgadmin:
    image: dpage/pgadmin4 # Using the official pgAdmin 4 image
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Replace with your desired login email
      PGADMIN_DEFAULT_PASSWORD: password      # Replace with a strong password
      PGADMIN_LISTEN_PORT: 80                 # pgAdmin's default web port
    ports:
      - "8080:80" # Map host port 8080 to pgAdmin's container port 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Persistent storage for pgAdmin configuration
    depends_on:
      - postgres # Ensure postgres starts before pgadmin

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres/embeddings
      REDIS_HOST: redis
    command: python worker.py
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres:5432/embeddings
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: "npm run dev"
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
