services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: embeddings
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/apph
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres:5432/embeddings
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     BACKEND_URL: http://backend:8000
  #   depends_on:
      # - backend

volumes:
  postgres_data: