services:
  test:
    image: nvcr.io/nvidia/rapidsai/base:23.12-cuda12.0-py3.10
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
